[formatting]
array_auto_collapse = false
array_auto_expand = false
array_trailing_comma = true
indent_string = "    "
align_comments = false


# Reorder dependencies
[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "*-dependencies"]

[rule.formatting]
reorder_keys = true


# Reorder features
[[rule]]
include = ["**/Cargo.toml"]
keys = ["features"]

[rule.formatting]
reorder_arrays = true
reorder_keys = true
