[package]
name = "aranya-example"
description = "Example Rust program using the Aranya client library"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

afc = ["aranya-client/afc", "aranya-client/preview"]

# Enable debugging.
debug = []

[dependencies]
aranya-client = { workspace = true }

anyhow = { workspace = true }
backon = { workspace = true }
rustix = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "process", "sync"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "aranya-example"
path = "src/main.rs"
required-features = ["afc"]
test = false
